function [ skinDecision ] = bayesianClassifier( pA, dA, aA, aD, mP, dP, mD, cD )

    global N...
         PMFRPA PMFBPA PMFGPA PMFDA PMFAA PMFMAD... 
         PMFDMPRU PMFMD PMFMP PMFCD

    skinDecision = 1;
    for i = 1:N        
        if (    PMFRPA( i, pA(1,1)+1 ) * PMFBPA( i, pA(1,2)+1 ) * PMFGPA( i, pA(1,3)+1 ) *...
                PMFDA( i, dA(1,1)+1 ) *...
                PMFAA( i, aA(1,1)+1 ) *...
                PMFMAD( i, aD(1,1)+1 ) *...
                PMFDMPRU( i, dP(1,1)+1 ) *...         
                PMFMD( i, mD(1,1)+1 ) *...
                PMFMP( i, mP(1,1)+1 ) *...
                PMFCD( i, cD(1,1)+1 ) >...
                PMFRPA( skinDecision, pA(1,1)+1 ) * PMFBPA( skinDecision, pA(1,2)+1 ) * PMFGPA( skinDecision, pA(1,3)+1 ) *...
                PMFDA( skinDecision, dA(1,1)+1 ) *...
                PMFAA( skinDecision, aA(1,1)+1 ) *...
                PMFMAD( skinDecision, aD(1,1)+1 ) *... 
                PMFDMPRU( skinDecision, dP(1,1)+1 ) *...           
                PMFMD( skinDecision, mD(1,1)+1 ) *...
                PMFMP( skinDecision, mP(1,1)+1 ) *...
                PMFCD( skinDecision, cD(1,1)+1 ) )
            
                skinDecision = i;
        end
    end       
end